apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: api-layer
    app.kubernetes.io/part-of: restructuraciones
    app.kubernetes.io/managed-by: gitlab-ci
    app.kubernetes.io/country: chile
  name: orders-svc
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: orders
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: api-layer
    app.kubernetes.io/part-of: restructuraciones
    app.kubernetes.io/managed-by: gitlab-ci
    app.kubernetes.io/country: chile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  orders-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: api-layer
      app.kubernetes.io/part-of: restructuraciones
      app.kubernetes.io/managed-by: gitlab-ci
      app.kubernetes.io/country: chile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: api-layer
        app.kubernetes.io/part-of: restructuraciones
        app.kubernetes.io/managed-by: gitlab-ci
        app.kubernetes.io/country: chile
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name:  orders
          image: hub.fif.tech/integracion-api/bfcl/orders:v0.0.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name:  orders-cfg
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          ports:
            - containerPort: 8080
              name: http
